# Generated by Django 5.2.4 on 2025-07-23 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmodel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skillsapp.usermodel'),
        ),
    ]
