# Generated by Django 5.2.8 on 2025-11-16 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmodel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skillsapp.usermodel'),
        ),
    ]
